<?php
$pets_grooming_slider_sc = pets_grooming_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $pets_grooming_slider_sc ) && strpos( $pets_grooming_slider_sc, '[' ) !== false && strpos( $pets_grooming_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( pets_grooming_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$pets_grooming_anchor_icon = pets_grooming_get_theme_option( 'front_page_title_anchor_icon' );
		$pets_grooming_anchor_text = pets_grooming_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $pets_grooming_anchor_icon ) || ! empty( $pets_grooming_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $pets_grooming_anchor_icon ) ? ' icon="' . esc_attr( $pets_grooming_anchor_icon ) . '"' : '' )
									. ( ! empty( $pets_grooming_anchor_text ) ? ' title="' . esc_attr( $pets_grooming_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $pets_grooming_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$pets_grooming_scheme = pets_grooming_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $pets_grooming_scheme ) && ! pets_grooming_is_inherit( $pets_grooming_scheme ) ) {
			echo ' scheme_' . esc_attr( $pets_grooming_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( pets_grooming_get_theme_option( 'front_page_title_paddings' ) );
		if ( pets_grooming_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$pets_grooming_css      = '';
		$pets_grooming_bg_image = pets_grooming_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $pets_grooming_bg_image ) ) {
			$pets_grooming_css .= 'background-image: url(' . esc_url( pets_grooming_get_attachment_url( $pets_grooming_bg_image ) ) . ');';
		}
		if ( ! empty( $pets_grooming_css ) ) {
			echo ' style="' . esc_attr( $pets_grooming_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$pets_grooming_anchor_icon = pets_grooming_get_theme_option( 'front_page_title_anchor_icon' );
		$pets_grooming_anchor_text = pets_grooming_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $pets_grooming_anchor_icon ) || ! empty( $pets_grooming_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $pets_grooming_anchor_icon ) ? ' icon="' . esc_attr( $pets_grooming_anchor_icon ) . '"' : '' )
									. ( ! empty( $pets_grooming_anchor_text ) ? ' title="' . esc_attr( $pets_grooming_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( pets_grooming_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' pets-grooming-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$pets_grooming_css      = '';
			$pets_grooming_bg_mask  = pets_grooming_get_theme_option( 'front_page_title_bg_mask' );
			$pets_grooming_bg_color_type = pets_grooming_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $pets_grooming_bg_color_type ) {
				$pets_grooming_bg_color = pets_grooming_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $pets_grooming_bg_color_type ) {
				$pets_grooming_bg_color = pets_grooming_get_scheme_color( 'bg_color', $pets_grooming_scheme );
			} else {
				$pets_grooming_bg_color = '';
			}
			if ( ! empty( $pets_grooming_bg_color ) && $pets_grooming_bg_mask > 0 ) {
				$pets_grooming_css .= 'background-color: ' . esc_attr(
					1 == $pets_grooming_bg_mask ? $pets_grooming_bg_color : pets_grooming_hex2rgba( $pets_grooming_bg_color, $pets_grooming_bg_mask )
				) . ';';
			}
			if ( ! empty( $pets_grooming_css ) ) {
				echo ' style="' . esc_attr( $pets_grooming_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$pets_grooming_caption = pets_grooming_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $pets_grooming_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $pets_grooming_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $pets_grooming_caption, 'pets_grooming_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$pets_grooming_description = pets_grooming_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $pets_grooming_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $pets_grooming_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $pets_grooming_description ), 'pets_grooming_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( pets_grooming_get_theme_option( 'front_page_title_button1_link' ) != '' || pets_grooming_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						pets_grooming_show_layout( pets_grooming_customizer_partial_refresh_front_page_title_button1_link() );
						pets_grooming_show_layout( pets_grooming_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
